language: python
dist: xenial
sudo: false
services:
  - docker
python:
  - "3.7"
install: 
  - pip install poetry
  - poetry install
  - docker pull hello-world
  # - npm ci
  # - npm run build
env:
  - BOTO_CONFIG=/dev/null AWS_DEFAULT_REGION=us-east-1 BOBSLED_SETTINGS_FILE=bobsled/tests/testconfig.yml
script: 
  - poetry run pytest
  - poetry run flake8
notifications:
  email:
    - dev@jamesturk.net
