language: python
dist: xenial
sudo: false
python:
    - "3.7"
install: 
    - pip install poetry
    - poetry install
    - npm ci
    - npm run build
script: 
    - poetry run pytest
    - poetry run flake8
notifications:
    email:
        - dev@jamesturk.net
