name: Backup-Mongo
entrypoint: /srv/openstates-web/scripts/backup
memory_soft: 128
cron: 0 0 * * ? *
enabled: False
environment:
    BILLY_MONGO_HOST: ec2-54-208-83-243.compute-1.amazonaws.com
    S3_BUCKET: openstates-backups
